# Generated by Django 4.2.6 on 2023-10-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEvento', models.CharField(max_length=100, verbose_name='Evento')),
                ('fechaInicio', models.DateTimeField(verbose_name='Inicio')),
                ('fechaFin', models.DateTimeField(verbose_name='Fin')),
            ],
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
    ]
