# Generated by Django 4.2.6 on 2023-10-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_evento_eventos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
    ]
