# Generated by Django 4.2.6 on 2023-10-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_eventos_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('urlLogo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'CompaniasInfo',
            },
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='email',
        ),
    ]
