# Generated by Django 4.2.6 on 2023-10-22 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_companiainfo_urllogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.companiainfo'),
            preserve_default=False,
        ),
    ]
