# Generated by Django 4.2.6 on 2023-10-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFormaPago', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esActivo', models.BooleanField(default=True)),
            ],
        ),
    ]
